//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealLifeJarvisServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealLifeJarvisServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //@@StartKeyword*********************
        /////open start play close exit search find google time date day weather report
        /////music alarm remind reminder home automation dictation help about backup restore settings outside
        /////hide weather report update name email
        /////@@EndKeyword******************
        /////******************************
        ///// Command 1a Start Program - Web-Page
        /////******************************
        ///hey travis i want you to open my Start run google facebook fiverr twitter youtube baidu wikipedia hotmail live y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //@@StartWeather****************************
        ///search get temprature of weather|Temprature of %City is %Temprature#1a
        ///show open display weather forcast panel|Displayed#1b
        ///show open display weather panel|Displayed#1c
        /////@@EndWeather******************************
        /////@@StartKeywordWeather*********************
        /////search find get temprature forcast weather
        /////@@EndKeywordWeather***********************
        /////@@StartUpdate****************************
        ///update get latest version|%data#1a
        /////@@EndUpdate**************** [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PanelCommands {
            get {
                return ResourceManager.GetString("PanelCommands", resourceCulture);
            }
        }
    }
}
